version: '3.9'

services:
  backend:
    build: ./backend
    container_name: library-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://library-mongo:27017/library_vadodara
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000/api  # ‚Üê ADD THIS LINE
    volumes:
      - ./frontend:/app
    command: npm start

  mongo:
    image: mongo:6
    container_name: library-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: